permalink: /:title

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  syntax_highlighter: rouge

#include:
# - _pages

collections:
  econ21020:
    output: true